DEEPSORT:
  REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7" #特征网络的预训练模型
  MAX_DIST: 0.2 #最近邻距离度量，马氏距离与余弦距离，用在级联匹配的地方，如果大于此距离，就直接忽略，不进行跟踪
  MIN_CONFIDENCE: 0.3 #yolo检测出来的置信度的阈值。小于该值的目标将被舍弃。【过大会导致图中一个人也测不出，过小会导致把其他物体错认为人。】
  NMS_MAX_OVERLAP: 0.5 #会筛选掉IOU重叠大于该值的框。【越大越容易检测重合的目标，例如一堆好基友聚会。但该值太大会导致把一个人认成不同的多个人重叠，并重复出现选框在同一目标上。】
  MAX_IOU_DISTANCE: 0.7 #IOU距离，当大于该数值时，认为是同一个目标，注意结果是1-Iou。【该值过大，会把不同的人认为是同一个人，在人多到时候乱跟随（“有奶就是娘”）。而太小会导致认为同一个人是不同的人，导致频繁的目标丢失，ID更迭。（“六亲不认”）】
  MAX_AGE: 70 #目标丢失时长（帧数）超过此数将被删除,代表一个Track存活期限，默认参数是70，对于运动速度快的需要减小该值。可以不严谨地总结为，记性好不好。鱼只有7秒记忆，狗应该会好一点……【如果值过大，可以记住长远一点的人，但更容易把不是那个人的人错认为原目标。过小则会频繁发生老年痴呆（阿尔兹海默症），只能记住很近出现的人，只要消失几秒，就忘了】
  #同时请注意，当画面中yolo没有检测出任何目标时，记忆是不会更新的，因此当画面中的人>=1时才会更新记忆！
  N_INIT: 3 #新目标confirm所需要的帧数,一回生二回熟，值决定了让他认识（确认）某个新人所需要的时间。
  NN_BUDGET: 100 #特征列表的长度，每个ID都有一个特征列表，此特征为ReID提取到的特征，如果超过，删除旧的 即 脑子能记住的人的总数。【过大也会导致记忆混乱，把张阿姨认成李阿姨】
